defaults:
  -
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -
   scope:
     type: posts
   values:
     permalink: /blogs/:year-:month-:day/:title.html

gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!--more-->

# Setup
title: Prof Rodney A. Kennedy
tagline: RSEng Engineering, CECS
description: 'Website of<br><b>Prof Rodney A. Kennedy</b><i class="fa fa-cog fa-spin fa-1x fa-fw"></i>'
hometitle: <i class="fa fa-institution fa-fw" aria-hidden="true"></i>&nbsp; Home Page
#lanyon-theme: 'theme-base-0b layout-reverse sidebar-overlay'
lanyon-theme: 'theme-base-0b sidebar-overlay'
resource-categories: [technote, code, paper, sphere, misc]

# A) Site served up locally usually on http://127.0.0.1:4003/
baseurl: ''
port: 4003

# excluded from copying to destination
exclude: [LICENSE.md, README.md, sandbox, assets/*latex, public/css/sandbox, a*.sh]

# about
name: Rod Kennedy
url: https://github.com/nerddonkey/raksite
email: rodney.kennedy@anu.edu.au

# version
version: 1.1.0
