# Permalinks, use of `relative_permalinks` ensures post links from the index work properly.
permalink: /blogs/:year-:month-:day/:title.html
relative_permalinks: true

# Setup
title: Prof Rodney A. Kennedy Homepage
tagline: College of Engineering and Computer Science
description: 'Website of Prof Rodney A. Kennedy'
port: 4001

# A) Site served up locally usually on http://127.0.0.1:4000/
#
baseurl: ''

# B) Site on ANU CECS servers
#
#baseurl: http://users.cecs.anu.edu.au/~rod/raksite

# C) Site hosted on Dropbox ~/Dropbox/Public/raksite
# available at https://dl.dropboxusercontent.com/u/3959788/raksite/index.html
#
#baseurl: https://dl.dropboxusercontent.com/u/3959788/raksite
#destination: /Users/rodneykennedy/Dropbox/Public/raksite

# max blogs entries per page
paginate: 5

# excluded from copying to destination
exclude: [sandbox]

# about
name: Rod Kennedy
url: https://github.com/nerddonkey/raksite
email: rodney.kennedy@anu.edu.au

# version
version: 1.0.0
